spring:
  output:
    ansi:
      enabled: ALWAYS


---
spring:
  profiles:
    active: dev
  timerName: exapleTimer
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: sys as sysdba
    password:



---
# MyBatis
mybatis:
  type-aliases-package: com.example.demo
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    mapUnderscoreToCamelCase=true
    aggressiveLazyLoading=false
    lazyLoadingEnabled=true
